# Faire rebondir une balle sur les bords

Cette démo comment faire rebondir une balle sur les bords de l'écran. 

Elle montre les principes de base
- afficher la fenêtre du jeu
- afficher une image de balle et la déplacer
- détecter la demande de sortie du programme

Le tutorial montre comment écrire le code étape par étape.

# PyGame

PyGame est un framework de jeu écrit en Python. 

Python est un langage de programmation. Il fait partie des plus simples à apprendre. Il est utilisé dans divers contextes professionnels comme  l'analyse de données et la robotique. 

PyGame apporte des fonctions qui rendent plus facile l'affichage d'image, la génération de sons et la gestion des collisions entre objets.

# Etape 1

Dans l'étape 1 nous allons nous familiariser avec le langage et apprendre à ouvrir la fenêtre du jeu

Le code complet est ci-dessous. Il est étudié en détail à la suite de ce code.

Tu peux copier ces lignes dans un fichier ball.py et le lancer par python ball.py pour voir ce qu'il fait.

In [3]:
#
# Faire rebondir une balle
# 01 - Afficher la fenêtre
#

# initialise pygame
import time, pygame
pygame.init()

# défini la largeur et la hauteur de la fenêtre
width = 320
height = 240

# print est une fonction qui affiche le contenu de la variable sur le terminal
print( width )

# window_size contient la paire de nombres largeur x hauteur
window_size = ( width, height )

# print affiche le contenu de window_size
print( window_size )

# défini la zone d'affichage
game_surface = pygame.display.set_mode(window_size)

# attend 5 seconde et ferme le programme
time.sleep(5)

320
(320, 240)


## Etude du programme étape 1

In [4]:
#
# Faire rebondir une balle
# 01 - Afficher la fenêtre
#

Les lignes qui commencent par # sont des commentaires. Elle servent seulement à comprendre ce que fait le programme.

In [5]:
# initialise pygame
import time, pygame
pygame.init()

(5, 1)

Le mot <b>import</b> indique le module de code que l'on veut utiliser. 

Un langage de programmation comme Python comporte de nombreuses fonctions. Elles sont rangées par modules qui regroupent des fonctions qui ont le même but.
- time contient des fonctions liées à la date et l"heure
- pygame contient les fonctions de PyGame

En utilisant le module pygame nous allons appeler la fonction init()

Cette fonction "initialise" l'environnement c'est à dire met en place ce qu'il faut pour que ça marche sur cette machine

Note que l'on a des . entre les mots. 

En python (et dans beaucoup de langages) on découpe les modules en fonctions qui réalisent une tâche donnée. On appelle une fonction dans un module particulier en utilisant &lt;nom du module&gt; . &lt;nom de la fonction&gt;

Une fonction peut avoir des paramètres. Par exemple, une fonction qui change la couleur aurait un paramètre couleur.

Les parenthèses ( ) entourent les paramètres de la fonction. Ici elle n'en a pas et la fonction s'écrit seulement init()

In [6]:
# défini la largeur et la hauteur de la fenêtre
width = 320 
height = 240

width et height sont des variables 

Elles permettent de définir la largeur et la hauteur de la fenêtre à afficher

La caractéristique d'une variable c'est qu'elle peut changer d'état au cours du temps. Mais son nom reste le même. 
On peut ainsi consulter l'état de la variable par son nom plus tard dans le programme


In [7]:
# affiche le contenu de la variable sur le terminal
print( width )

320


print est une fonction qui affiche le contenu de la variable sur le terminal

In [8]:
# window_size contient la paire de nombres largeur x hauteur
window_size = ( width, height )

window_size est aussi une variable. 

Au lieu de contenir simplement un nombre elle contient une paire de nombres. width et height vont être remplacés par la valeur de width et height définie plus haut.

In [9]:
# affiche le contenu de window_size
print( window_size )

(320, 240)


print affiche les valeurs sous une forme adaptée à sa structure, ici (320, 240)

Les parenthèses indiquent que c'est une liste, c'est à dire une suite de valeurs.

screen est une variable qui est construite par la fonction display de pygame

pygame a besoin  d'informations par exemple window_size. Ces informations sont passées par la fonction set_mode

In [10]:
# défini la zone d'affichage
game_surface = pygame.display.set_mode(window_size)

game_surface est une variable qui est construite par la fonction display de pygame

pygame a besoin  d'informations par exemple window_size. Ces informations sont passées par la fonction set_mode.

In [11]:
time.sleep(5)
quit()

Si tu lances le programme tu va le voir s'afficher 5 secondes et s'arrêter

In [1]:
python ball.py

## Coder le programme 

Ouvre l'éditeur de code.

Crée un fichier ball.py et copie les lignes de code.

Lance le programme en utilisant l'éditeur ou la commande en ligne python ball.py.


## Modifier le programme étape 1

A ce stade tu peux faire quelques changement comme modifier la taille de la fenêtre pour l'adapter à la taille de ton écran.

# Etape 2

Dans l'étape 1, le programme démarrait pour 5 secondes et s'arrêtait. 

Dans l'étape 2 nous voir comment gérer les événements provoqués par le joueur. On va prendre un cas simple, la sortie pour le bouton de fermeture de la fenêtre.

Ce programme est complet et remplace celui de l'étape 1

In [ ]:
#
# Faire rebondir une balle
# 02 - Gérer la sortie du programme
#

# initialise pygame
import pygame
pygame.init()

# défini la zone d'affichage
width = 320
height = 240
window_size = ( width, height )
game_surface = pygame.display.set_mode(window_size)

# boucle infinie
running = True
while running:
    for event in pygame.event.get():
        # pour le bouton de fermeture de la fenêtre, quitte le programme
        if event.type == pygame.QUIT:
          running = False


## Etude du programme étape 2

Certaines parties sont identiques par rapport à l'étape précédente et ne sont pas rappellées.

Un jeu nécessite en général de gérer des interactions avec le joueur.

Lorsque le joueur utilise le clavier ou les boutons de la fenêtre, l'ordinateur envoie des messages au programme. 

Ces messages s'appellent des évèvements et les programmes de ce type utilisent une boucle d'événement pour les attraper et les traiter.

Dans notre exemple, 1 type d'évenement est traités 
- la fermeture de la fenêtre et l'arrêt du jeu

D'autres événements sont gérés par un moyen similaire
- les touches flèche pour déplacer la balle
- les déplacements de la souris et les boutons


Les messages arrivent tout le temps. PyGame va les collecter, les mettre en file d'attente et les enverra lorsqu'on demande les évenéments arrivés.

Le programme fait une suite d'opérations dans une boucle :
- lire un événement
- traiter cet événement 
- réafficher pour montrer le résultat

Cette boucle s'arrête lorsque le jeu détermine que la partie est terminée ou lorsque le joueur ferme la fenêtre.

La partie qui nous intéresse est ici

In [ ]:
# boucle infinie
running = True
while running:
    for event in pygame.event.get():
        # pour le bouton de fermeture de la fenêtre, quitte le programme
        if event.type == pygame.QUIT:
          running = False


Cette section contient ce qu'on appelle la boucle d'événement. C'est là que tout va se passer.

In [ ]:
running = True
while running:
    ...
              running = False


while est une instruction de boucle. Elle signifie Tant que. 

Le programme va continuer tant que la condition running reste vrai. 

- Elle est vrai au départ parce que running est initialisé à True (vrai). 
- Plus tard cette variable va passer à False (faux) et là le programme s'arrêtera.

running est une variable de type booléen, c'est à dire quelle n'a que 2 valeurs True ou False. 

Ce type de variable est utilisé lorsque l'on a besoin de condition, pour déterminer si on continu ou dans quelle partie du code on doit aller après.

In [ ]:
    for event in pygame.event.get():

pygame.event.get() est une fonction qui retourne la liste des événements en file d'attente.

<b>for</b> est une instruction qui permet aussi de faire une boucle mais différemment de while. 

<b>while</b> attend une condition. <b>for</b> va faire une boucle pour un certain nombre de fois, ou pour chaque éléments d'une liste.

<b>for event in pygame.event.get()</b> permet de parcourir toute la liste et pour chaque élément de la liste on pourra utiliser event pour représenter cet événement.

<b>event</b> est un objet. Un objet représente un concept ou un élément que l'on peut manipuler dans le jeu.

Un objet a un contenu (par exemple le type de l'objet). On parle plutôt d'attributs dans ce cas. Les attributs sont obtenus en écrivant < nom l'objet > . < nom de l'attribut >.

Un objet a aussi des opérations qui permettent de modifier le contenu ou de faire les tâches dont l'objet est responsable. Ce sont des fonctions.

Tu peux ajouter un print(event) dans la boucle for pour voir le contenu des énénements reçus.

In [ ]:
        # pour le bouton de fermeture de la fenêtre, quitte le programme
        if event.type == pygame.QUIT:
          running = False

<b>if</b> permet de vérifier si la condition qui suit est vrai et entrer dans cette partie du code si c'est le cas.

La condition testée est event.type == pygame.QUIT

- <b>event.type</b> indique qu'on veut lire la valeur "type" dans l'événement

- <b>pygame.QUIT</b> indique une valeur qui correspond à cet évenement. 

- <b>==</b> indique que l'on veur comparer les 2 valeurs. 

Attention: 

- = signifie que l'on veut que la variable qui est à gauche du = reçoive la valeur qui est à droite du =. 

- == signifie qu'on veut vérifier que les valeurs sont égales. Le résultat est une variable que contient vrai ou faux (True ou False) et qu'on appelle un booléen.

QUIT est en majuscule parce que c'est une constante définie dans le module pygame. Sa valeur ne change pas (ici c'est 12). Une constante s'utilise comme une variable, à la différence que sa valeur ne peut être définie qu'une seule fois.

Si la condition est vrai, la fin du programme est demandées en changeant running pour False.

## Coder le programme de l'étape 2

Ouvre l'éditeur de code.

Crée un fichier ball.py et copie les lignes de code.

Lance le programme en utilisant l'éditeur ou la commande en ligne python ball.py.


# Etape 3

Dans l'étape 3 nous voir comment ajouter un fond et une image.

Ce programme est complet et remplace celui de l'étape 2

In [ ]:
#
# Faire rebondir une balle
# 03 - Afficher la balle
#

# initialise pygame
import pygame
pygame.init()

# défini la zone d'affichage
width = 320
height = 240
window_size = ( width, height )
game_surface = pygame.display.set_mode(window_size)

# défini la couleur noire pour le fond
color_black = ( 0, 0, 0 )

# charge l'image de la balle
ball_image = pygame.image.load("ball.bmp")
ball_rect = ball_image.get_rect()

# boucle infinie
running = True
while running:
    for event in pygame.event.get():
        # pour le bouton de fermeture de la fenêtre, quitte le programme
        if event.type == pygame.QUIT:
          running = False

    # reaffiche le fond et la balle
    game_surface.fill(color_black)
    game_surface.blit(ball_image, ball_rect)
    pygame.display.flip()


## Etude du programme étape 3

Certaines parties sont identiques par rapport à l'étape précédante et ne sont pas rappellées.

In [ ]:
# défini la couleur noire pour le fond
color_black = ( 0, 0, 0 )

Pour l'affichage sur écran les couleurs sont définies par 3 nombres.

Ces nombres représentent la quantité de rouge (R), de vert (G), de bleu (B). Ce code s'appelle RGB.

La valeur minimale est 0 (pas de lumière) et le maximum est 255 (maximum de lumière)

Par exemple, 255 255 255 représente du blanc, 255 0 0 représente du rouge vif. 0 0 0 est une absence de lumière donc du noir

In [ ]:
# charge l'image de la balle
ball_image = pygame.image.load("ball.bmp")
ball_rect = ball_image.get_rect()

load est une fonction du module image qui change un fichier image (ici ball.bmp)

ball.get_rect() permet d'obtenir les dimensions de l'image chargée



In [ ]:
    # reaffiche le fond et la balle
    game_surface.fill(color_black)
    game_surface.blit(ball_image, ball_rect)
    pygame.display.flip()


<b>game_surface.fill</b> est une fonction de l'objet Surface qui rempli la surface avec la couleur passée en paramètre.

Ici on l'utilise pour repeindre le fond.

<b>game_surface.blit</b> est une fonction de l'objet Surface qui copie l'image de la balle dans le rectangle défini par ball_rect

Ces modifications sont faites sur une zone non visible pour éviter qu'on voit le dessin en cours

<b>flip</b> copie l'objet Surface copié sur l'écran

Cette ligne doit être à la fin du dessin, après TOUTES les instructions d'affichage

## Coder le programme de l'étape 3

Ouvre l'éditeur de code.

Crée un fichier ball.py et copie les lignes de code.

Lance le programme en utilisant l'éditeur ou la commande en ligne python ball.py.



## Modifier le programme étape 3

A ce stade tu peux changer les couleurs ou les images.

Le programme a besoin d'une image au format .bmp (Bitmap) ou PNG dans le même dossier que le programme. Tu peux copier d'autres images ou en fabriquer avec Gimp.

# Etape 4

Dans l'étape 4 nous voir comment déplacer la balle.

Ce programme est complet et remplace celui de l'étape 3

In [ ]:
#
# Faire rebondir une balle
# 04 - Déplacer la balle
#

# initialise pygame
import pygame
pygame.init()

# défini la zone d'affichage
width = 320
height = 240
window_size = ( width, height )
game_surface = pygame.display.set_mode(window_size)

# défini la couleur noire pour le fond
color_black = ( 0, 0, 0 )

# charge l'image de la balle
ball_image = pygame.image.load("ball.bmp")
ball_rect = ball_image.get_rect()

# boucle infinie
running = True
while running:
    for event in pygame.event.get():
        # pour le bouton de fermeture de la fenêtre, quitte le programme
        if event.type == pygame.QUIT:
          running = False

    # recalcule la position
    ball_rect = ball_rect.move( [2, 1] )

    # reaffiche le fond et la balle
    game_surface.fill(color_black)
    game_surface.blit(ball_image, ball_rect)
    pygame.display.flip()


## Etude du programme étape 4

Certaines parties sont identiques par rapport à l'étape précédente et ne sont pas rappellées.

Pour déplacer la balle, on ca simplement modifier son rectangle d'affichage

In [ ]:
    # recalcule la position
    ball_rect = ball_rect.move( [2, 1] )

Ce rectangje a été obtenu par la fonction get_rect() de l'image.

Cet objet a divers attributs qui permettent d'obtenir sa position :
- x,y : qui définissent les coordonnées d'affichage du coin en haut à gauche du rectangle dans la surface game_surface. x est la position horizontale. y est la position verticale. Dans PyGame, le coin en haut à gauche de la surface est 0, 0 et les coordonnées sont croissantes vers la droite et le bas  
- w,h, width, height : qui définissent sa largeur (width ou w) et sa hauteur (height ou h)
- size : renvoie un couple width et  height
- center, topleft, bottomleft, topright, bottomright : renvoient un point de coordonnées (x, y)
- centerx, centery, midtop, midleft, midbottom, midright : renvoient aussi des points de coordonnées (x, y)
- top, left, bottom, right : renvoient une valeur de x (left, right) ou y (top, bottom)


Cet objet a aussi des opérations comme move qui permet de déplacer le rectangle de l'image par rapport à la Surface. 

Le paramètre passé à move est un vecteur (x, y) du déplacement à effectuer. Ici à chaque passage dans la boucle l'image est déplacée de 2 pixels vers à droite (x+2) et 1 pixel vers le bas (y+2).

collidepoint, colliderect qui renvoie True ou False et permettent de vérifier si un rectangle contient un autre point ou rectangle et qui seront utilisés pour la détecion de collision entre objets de la scène.

## Coder le programme de l'étape 4

Ouvre l'éditeur de code.

Crée un fichier ball.py et copie les lignes de code.

Lance le programme en utilisant l'éditeur ou la commande en ligne python ball.py.


## Modifier le programme étape 4

A ce stade tu peux changer le sens de déplacement et la vitesse.

# Etape 5

Dans l'étape 5 nous voir comment faire rebondir la balle.

Ce programme est complet et remplace celui de l'étape 4

In [ ]:
#
# Faire rebondir une balle
# 05 - Gérer le rebond
#

# initialise pygame
import pygame
pygame.init()

# défini la zone d'affichage
width = 320
height = 240
window_size = ( width, height )
game_surface = pygame.display.set_mode(window_size)

# défini la couleur noire pour le fond
color_black = ( 0, 0, 0 )

# charge l'image de la balle
ball_image = pygame.image.load("ball.bmp")
ball_rect = ball_image.get_rect()

# initialise le vecteur de déplacement
ball_speed = [5, 5]
X = 0
Y = 1

# boucle infinie
running = True
while running:
    for event in pygame.event.get():
        # pour le bouton de fermeture de la fenêtre, quitte le programme
        if event.type == pygame.QUIT:
          running = False

    # recalcule la position
    ball_rect = ball_rect.move(ball_speed)

    # rebond sur les bords gauche et droit
    if ball_rect.left < 0 or ball_rect.right > width:
        ball_speed[X] = -ball_speed[X]

    # rebond sur les bords haut et bas
    if ball_rect.top < 0 or ball_rect.bottom > height:
        ball_speed[Y] = -ball_speed[Y]

    # reaffiche le fond et la balle
    game_surface.fill(color_black)
    game_surface.blit(ball_image, ball_rect)
    pygame.display.flip()


## Etude du programme étape 5

Certaines parties sont identiques par rapport à l'étape précédente et ne sont pas rappellées.

In [ ]:
Le déplacement est similaire mais on va calculer le déplacement à chaque étape.

In [ ]:
# initialise le vecteur de déplacement
ball_speed = [5, 5]


Le déplacement est défini par un vecteur. Au départ, la balle se déplace de 5 pixels en x et y à chaque passage dans la boucle de programme.

Dans ce vecteur 
- la première valeur ball_speed[0] représente x
- la deuxième valeur ball_speed[1] représente y

ball_speed est un tableau. Dans un tableau les valeurs sont accessibles par leur position et la première position est 0.

In [ ]:
X = 0
Y = 1

X et Y sont définis pour rendre le programme plus lisible. 
- ball_speed[X]
- ball_speed[Y]

X et Y sont des constantes (leur valeur ne changera jamais) qui désignent la position 0 et 1 de manière plus lisible.

In [ ]:
    # recalcule la position
    ball_rect = ball_rect.move(ball_speed)

Le déplacement n'est plus écrit en dur. Il est passé par une variable que l'on pourra modifier.

Lorsque la balle touche le bord, le vecteur de déplacement est modifié
- sur les bords gauche et droit, le rebond inverse la vitesse horizonale
- sur les bords gauche et droit, le rebond inverse la vitesse verticale 

Le bord est touché quand la valeur correspond à 0 ou la valeur maximale
- à gauche le minimum est 0
- à droite le maximum est width
- en haut le minimum est 0
- en bas le maximum est height



In [ ]:
    # rebond sur les bords gauche et droit
    if ball_rect.left < 0 or ball_rect.right > width:
        ball_speed[X] = -ball_speed[X]

    # rebond sur les bords haut et bas
    if ball_rect.top < 0 or ball_rect.bottom > height:
        ball_speed[Y] = -ball_speed[Y]


Les deux conditions <b>if</b> utilisent le mot <b>or</b> pour vérifier que l'une ou l'autre des conditions est atteinte.

Il existe aussi le mot <b>and</b> si l'on veut vérifier que toutes les conditions sont atteintes.